### PR TITLE
Feature create edit view for items in admin namespace

### PR DESCRIPTION
**Pull request by stephan-dev**
Petite branche devenue grande.
Fix admin items controller
Make all views and forms (fix problem with forms and items in admin namespace)

Pour l'instant accès au dashboard par la barre d'adresse : administration/items

Small design conflict : worked with small pics (css), doesn't work with latest update

Qui a effacé toutes les issues qui restaient à faire et qui sont fix par cette PR ??
Dû refaire une spec rapidos #112

### CODE REVIEW

**Review by Crysicia — CHANGES_REQUESTED** [review]
Seems good, but why did you remove the conditions `if save ... else render new` ?

**Comment by stephan-dev** [comment]
> Seems good, but why did you remove the conditions `if save ... else render new` ?

Good point. Was completely exhausted and remembered that in the metro. I also should have said that I did the front for 2 views, fronts needs to be done for index and show, I think. 
I'm putting that condition back.

**Comment by stephan-dev** [comment]
I just tested with bogus item creation. The deleted condition, put back, doesn't work (for example : original price is empty). Needs to be improved more. Maybe also put back the new and save, rather than create

**Review by Crysicia — APPROVED** [review]

**Comment by stephan-dev** [comment]
fixed front (image sizes...), fixed conditions with missing validations

**Review by Crysicia — APPROVED** [review]
Next time don't put CSS in HTML please :)

**Review by MelloFlo — APPROVED** [review]

**Pull request merged**
